### ISSUE TITLE
NullPointerException in ListReleases

### ISSUE THREAD

**Issue by Towmeykaw** [qmfrederik/helm#10]
Hello. Im getting a NullPointerException when not specifying a filter for ListReleases. Since it has a default value im guessing thats not intended. When specifying an empty string all works as expected.

**Comment by qmfrederik** [comment]
Do you have a stack trace? I assume it's the serialization code which barks at the `null` value, but want to be sure.

**Comment by Towmeykaw** [comment]
All i get is 
"Value cannot be null. Parameter name: value" 

Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)  
at Helm.Helm.TillerClient.ListReleases(String filter, Int32 limit, String namespace, String offset, SortBy sortBy, SortOrder sortOrder, IEnumerable`1 statusCodes, CancellationToken cancellationToken)

**Comment by qmfrederik** [comment]
OK - it looks like protobuf doesn't handle `null` values for strings very well and we should set the default to be to `string.Empty`. Care to send a PR? 😄 .

**Comment by Towmeykaw** [comment]
Sounds good :D

**Comment by Towmeykaw** [comment]
Added a PR
