### ISSUE TITLE
secure channel to connect to tiller server

### ISSUE THREAD

**Issue by YasGupta** [qmfrederik/helm#14]
I am trying to create a secure channel by providing ssl certificates while creating the channel. I added another constructor for TillerClient that accepts the Grpc.Core.SslCredentials and creates the channel using those certifcates (new Channel(target, clientCredentials). But that doesn't seem to work. The same certificates works for the helm command line tool. 

Is there any other way I can get the TLS authentication working ?

**Comment by qmfrederik** [comment]
I assume you've enabled TLS authentication on Tiller as described [here](https://github.com/helm/helm/blob/master/docs/tiller_ssl.md)?

If so, that isn't a scenario I have looked at yet.

I think you might be able to:
- Create a function which sets up a TLS session with the Tiller server using the `SslStream` class and call [`AuthenticateAsClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclient?redirectedfrom=MSDN&view=netframework-4.7.2#System_Net_Security_SslStream_AuthenticateAsClient_System_String_System_Security_Cryptography_X509Certificates_X509CertificateCollection_System_Security_Authentication_SslProtocols_System_Boolean_)
- Pass that function to the ` TillerClient(Func<Stream> stream)` constructor of the `TillerClient`

**Comment by YasGupta** [comment]
Thanks ! I was able to get it working with a secure channel. TLS_VERIFY flag was on and the certificates did not have the proper SAN. I am now creating a channel and passing in that but would need a new constructor. I will put up a pull request to add a new constructor.
